### ISSUE TITLE
Points, In:s and commas

### ISSUE THREAD

**Issue by BythewayMichael** [maieul/biblatex-multiple-dm#1]
Hello! 

I am using biblatex-multiple-dm and I find it fantastic. Still, I would like to introduce two changes in the style and I don't know how to do it.

1) I would like to have commas instead of dots.
2) change . In: xxx XXX --> , in xxx XXX [for all cases except point 3)]
3) no . In: nor , in for articles

A mock page follows.

How can I do it? I am using XeLaTex. If my wish for point 1 could be neglected if impossible to be solved [and if so, point 2 as a consequence], I would like to remove those In:s from articles...

Thank you for your attention!

%--------------------------------------------------------------------------------------------------------------

% !TeX encoding = UTF-8
% !TeX TS-program = xelatex
% !TeX spellcheck = en_GB
% !TeX root = Test.tex
% !BIB TS-program = biber

\documentclass[a4paper,12pt]{article}

\usepackage[%
	tools={morenames,bookinother},%
	bibstyle=verbose%
	]{biblatex-multiple-dm}
\usepackage[%
	backend=biber,%
	style=multiple-dm,%
	citestyle=authoryear,%
	autolang=other,%
    dashed = true,%
	sorting=nyt,%
	indexing]{biblatex}

\addbibresource{bibliography.bib}

\begin{filecontents}{bibliography.bib}
@Book{clone,
  author = {Maniatis, T. and Fritsch, E. F. and Sambrook, J.},
  title = {Molecular Cloning: A Laboratory Manual},
  year = {2001},
  publisher = {Cold Spring Harbor Laboratory},
  location = {New York},
  edition = {3}}
  

@incollection{Hello,
 author = {Beans, Mister},
 title = {Just a Mock Article},
 Crossref = {clone},
 pages = {163--180}
}

  @article{Frankam.1995,
 author = {Frankam, Richard},
 year = {1995},
 title = {Conservation Genetics},
 pages = {305-327},
 volume = {29},
 journal = {Annual Review of Genetics}
}
\end{filecontents}

\begin{document}

Hello
\cite{Frankam.1995}
\cite{Hello}

\nocite{*}
\printbibliography

\end{document}

**Comment by BythewayMichael** [comment]
I have noticed that my filecontents doesn't create the voice for "incollection", but if you copy my mock entries in a bib file it works! Sorry for this inconvenience.

**Comment by maieul** [comment]
I think your problem is related to bookinother, as biblatex-multiple-dm 
does not provide anystyle.

So please open a issue in the good repository

**Comment by BythewayMichael** [comment]
Ok, thank you!
